import tkinter as tk
from tkinter import messagebox

# ═══════════════════════════════════════════════════════════
#  ISMLAR MA'NOSI — KENG KAMUS (400+ ISM)
# ═══════════════════════════════════════════════════════════
ISMLAR = {
    # ===== O'G'IL ISMLARI =====
    "abdulloh": "Allohning quli, Allohga bo'ysunuvchi",
    "abdurahmon": "Mehribon Allohning quli",
    "abdulaziz": "Ulug' Allohning quli",
    "abdullatif": "Latif Allohning quli",
    "abduqodir": "Qodir Allohning quli",
    "abdullo": "Allohning quli",
    "abdunabi": "Payg'ambarga qullik qiluvchi",
    "abdusalom": "Salom beruvchining quli",
    "abduvohid": "Yagona Allohning quli",
    "abror": "Yaxshiliklar, ezgu ishlar",
    "abdulhamid": "Maqtovga loyiq Allohning quli",
    "abduljabbor": "Qahhor Allohning quli",
    "abdulkarim": "Karim Allohning quli",
    "abdulmalik": "Malik Allohning quli",
    "abdulrashid": "Rashid Allohning quli",
    "abdulqahhor": "Qahhor Allohning quli",
    "abdulbasit": "Bosit Allohning quli",
    "abdulla": "Allohning sodda quli",
    "abdulmo'min": "Mo'minlarning quli",
    "abdulboriy": "Boriy Allohning quli",
    "abdulmuqit": "Muqit Allohning quli",
    "abulqosim": "Qosimning otasi",
    "adham": "Qora, ko'k",
    "adil": "Adolatli, haqqoniy",
    "adilbek": "Adolatli + bek",
    "adiljon": "Adolatli + jon",
    "ahmad": "Maqtovga sazovor",
    "ahmadjon": "Maqtovli + jon",
    "ahror": "Hur, erkin insonlar",
    "akbar": "Eng buyuk, ulkan",
    "akbarali": "Eng buyuk + Ali",
    "akbarbek": "Eng buyuk + bek",
    "akbarjon": "Eng buyuk + jon",
    "akmal": "Mukammal, to'liq",
    "alim": "Ilmli, bilimli",
    "alimbek": "Ilmli + bek",
    "alimjon": "Ilmli + jon",
    "ali": "Oliy, yuksak, yuqori martabali",
    "alibek": "Yuksak + bek",
    "alijon": "Yuksak + jon",
    "olim": "Bilimdon, olim inson",
    "olimjon": "Bilimdon + jon",
    "amir": "Podsho, buyruqchi, boshliq",
    "amirbek": "Boshliq + bek",
    "amirjon": "Podsho + jon",
    "amirali": "Podsho + Ali",
    "amin": "Ishonchli, ishonch bilan",
    "aminbek": "Ishonchli + bek",
    "aminjon": "Ishonchli + jon",
    "anas": "Do'st, sirdosh, inson",
    "anvar": "Yorqin, porloq, nurlanuvchi",
    "anvarbek": "Yorqin + bek",
    "anvarjon": "Yorqin + jon",
    "arbob": "So'z ustasi, ma'rifatli",
    "asl": "Asl, tub, asosiy",
    "aslan": "Sher, jasur, baquvvat",
    "asliddin": "Dinning asli",
    "asror": "Sirlar, sirli narsalar",
    "asrorbek": "Sirli + bek",
    "asrorjon": "Sirli + jon",
    "asil": "Aslzoda, olijanob",
    "asilbek": "Aslzoda + bek",
    "asomiddin": "Dinning himoyachisi",
    "ataliq": "Otadek mehribon, murabbiy",
    "atif": "Mehribon, shafqatli",
    "atobek": "Ota + bek",
    "atojon": "Ota + jon",
    "ayub": "Sabrli, qaytgan",
    "azamat": "Ulug'vorlik, qadr-qimmat",
    "azamatbek": "Ulug'vor + bek",
    "aziz": "Aziz, qadrli, hurmatli",
    "azizbek": "Aziz + bek",
    "azizjon": "Aziz + jon",
    "azim": "Ulug', buyuk, a'zam",
    "azimbek": "Buyuk + bek",
    "azimjon": "Ulug' + jon",
    "badriddin": "Dinning to'lin oyi",
    "bahodir": "Qahramon, jasur, botir",
    "bahodirbek": "Botir + bek",
    "bahrom": "G'alabali, zafarli",
    "bakhtiyor": "Baxtli, baxtiyor",
    "baxtiyor": "Baxtli, baxtga erishgan",
    "baxtiyorjon": "Baxtli + jon",
    "bahodirjon": "Botir + jon",
    "baloyiddin": "Dinning yuksakligi",
    "baxt": "Omad, baxt, farovonlik",
    "baxtiyor": "Baxtli, baxtga erishgan",
    "bek": "Hukmdor, rahbar, lord",
    "bekzod": "Bekning farzandi",
    "bekmurod": "Bek + murod",
    "bilol": "Toza suv, bilol",
    "bohir": "Ochiq, ravshan, yorqin",
    "boris": "Kurashchi, qahramon",
    "botir": "Jasur, qo'rqmas",
    "botirjon": "Jasur + jon",
    "daler": "Jasur, botir, qo'rqmas",
    "daniyor": "Donishmand, aqlli",
    "danil": "Alloh mening hakamim",
    "daulat": "Boylik, davlat, boylik",
    "davriddin": "Dinning asri",
    "dildor": "Dil sohibi, sevgan",
    "dilmurod": "Dil + murod, ko'ngildagi murod",
    "dilshod": "Ko'ngli xursand, shod",
    "dilshodbek": "Xursand + bek",
    "dilshodjon": "Xursand + jon",
    "doston": "Hikoya, doston",
    "dostonbek": "Doston + bek",
    "dostonjon": "Doston + jon",
    "eldor": "El + dor, elni sevuvchi",
    "eldorjon": "El + dor + jon",
    "elshod": "El + shod, elni xursand qiluvchi",
    "elbek": "El + bek, el boshchisi",
    "elyor": "El yori, do'sti",
    "elchi": "El elchisi",
    "elgun": "El quyoshi",
    "elmir": "El amiri",
    "elsun": "El eshitgan",
    "elyorjon": "El yori + jon",
    "erkam": "Erkin, azizim",
    "erkin": "Hur, erkin, ozod",
    "erkinbek": "Erkin + bek",
    "erkinjon": "Erkin + jon",
    "erman": "Erka + inson",
    "ernazar": "Erkak + nazar",
    "erzod": "Erka + zod",
    "farrux": "Baxtli, farovon, yuzi yorqin",
    "fayzulloh": "Allohning fayzi, in'omi",
    "fayziddin": "Dinning fayzi",
    "farhod": "Qahramon, sevgi ramzi",
    "faridun": "Uch podshoh, adolatli",
    "firdavs": "Jannat bog'i, yuksak jannat",
    "firuz": "G'alabali, zafarli",
    "fotih": "G'olib, ochuvchi",
    "fotihbek": "G'olib + bek",
    "fotihjon": "G'olib + jon",
    "foyiz": "Katta, ko'p, mo'l",
    "furqat": "Ajralish, ayriliq",
    "g'ani": "Boy, boylik sohibi",
    "g'ofir": "Kechiruvchi, mag'firatli",
    "g'ulom": "Yigit, xizmatkor",
    "hamid": "Maqtovga loyiq",
    "hamidjon": "Maqtovli + jon",
    "hamza": "Sherdek jasur",
    "hasan": "Yaxshi, go'zal, husnli",
    "hasanali": "Yaxshi + Ali",
    "hasanbek": "Yaxshi + bek",
    "hasanjon": "Yaxshi + jon",
    "hikmat": "Donolik, aql-idrok",
    "hikmatulloh": "Allohning hikmati",
    "homid": "Maqtovchi, shukr qiluvchi",
    "hoshim": "Non ushatuvchi, saxiy",
    "hoshimbek": "Hoshim + bek",
    "hoshimjon": "Hoshim + jon",
    "hotam": "Saxiy, mehmondo'st",
    "husan": "Yaxshi, go'zal (hasan varianti)",
    "husanboy": "Yaxshi + boy",
    "husanjon": "Yaxshi + jon",
    "husniddin": "Dinning husni, go'zalligi",
    "ibodat": "Ibodat qiluvchi",
    "ibn": "O'g'il",
    "idris": "O'qituvchi, ma'rifat sohibi",
    "ilmiddin": "Ilmli, dinni biluvchi",
    "imron": "Obod qiluvchi, farovon",
    "islom": "Islom diniga mansub, tinchlik",
    "islombek": "Islom + bek",
    "islomjon": "Islom + jon",
    "is'hok": "Kulgu, quvonch",
    "isroil": "Allohning bandasi",
    "izzat": "Hurmat, sharaf, qadr-qimmat",
    "izzatulloh": "Allohning izzati",
    "izzatbek": "Hurmat + bek",
    "izzatjon": "Hurmat + jon",
    "jobir": "Tuzatuvchi, qayta tiklovchi",
    "jasur": "Botir, qo'rqmas, jasur",
    "jasurbek": "Jasur + bek",
    "jasurjon": "Jasur + jon",
    "javlon": "Shovqin, g'avg'o, jasorat",
    "jafar": "Kichik daryo, ko'p oqadigan",
    "jamoil": "Chiroyli, go'zal",
    "jamoliddin": "Dinning go'zalligi",
    "jamshid": "Podshoh, yorqin",
    "jangir": "Jangchi, jang qiluvchi",
    "javohir": "Javohirlar, qimmatbaho toshlar",
    "javon": "Yosh, yigit",
    "javohirbek": "Javohir + bek",
    "jayhun": "Daryo nomi, katta daryo",
    "jura": "Jur'atli, jasur",
    "kamol": "Kamolga yetgan, mukammal",
    "kamoliddin": "Dinning kamoli",
    "karim": "Saxiy, karamli, rahmli",
    "karimbek": "Karim + bek",
    "karimjon": "Karim + jon",
    "kavus": "Podshoh, hukmdor",
    "keyson": "Katta, keng, ulkan",
    "komil": "Mukammal, yetuk",
    "komilbek": "Mukammal + bek",
    "komiljon": "Mukammal + jon",
    "kudratulloh": "Allohning qudrati",
    "kudrat": "Quvvat, kuch, qudrat",
    "kudratbek": "Quvvat + bek",
    "la'l": "Qimmatbaho tosh, yoqut",
    "lavangi": "Lavang daraxti",
    "lutfulla": "Allohning lutfi, mehribonligi",
    "lutfilloh": "Allohning lutfi",
    "lutfiddin": "Dinning lutfi",
    "madiyor": "Madhiya aytuvchi, maqtovchi",
    "majid": "Ulug', buyuk, shonli",
    "mahmud": "Maqtalgan, hamd etilgan",
    "mahmudjon": "Maqtalgan + jon",
    "mansur": "G'olib, g'alaba qozonuvchi",
    "mansurbek": "G'olib + bek",
    "mansurjon": "G'olib + jon",
    "maruf": "Yaxshi, ma'lum, tanilgan",
    "maruflbek": "Yaxshi + bek",
    "marufjon": "Yaxshi + jon",
    "mehribon": "Mehribon, shafqatli",
    "mehribonjon": "Mehribon + jon",
    "mehroj": "Mehribon + oj",
    "mehrod": "Mehribon + rod",
    "mehroli": "Mehribon + Ali",
    "mardon": "Erkak, jasur, mard",
    "mardonbek": "Mard + bek",
    "mardonjon": "Mard + jon",
    "mashhur": "Mashhur, tanilgan",
    "matlub": "Istak, tilak, arzu",
    "maxmud": "Maqtalgan",
    "maxmudbek": "Maqtalgan + bek",
    "maxmudjon": "Maqtalgan + jon",
    "mumin": "Mo'min, ishongan, imonli",
    "muminbek": "Mo'min + bek",
    "muminjon": "Mo'min + jon",
    "murod": "Istak, orzu, tilak",
    "murodali": "Murod + Ali",
    "murodbek": "Murod + bek",
    "murodjon": "Murod + jon",
    "muzaffar": "G'olib, zafar qozonuvchi",
    "muzaffarbek": "G'olib + bek",
    "muzaffarjon": "G'olib + jon",
    "muhammad": "Maqtalgan, ko'p maqtalgan",
    "muhammadali": "Muhammad + Ali",
    "muhammadi": "Muhammadga oid",
    "muhammadjon": "Muhammad + jon",
    "muhammadali": "Maqtalgan + Ali",
    "muhammadsolih": "Muhammad + solih",
    "muhammadsharif": "Muhammad + sharif",
    "muhammadqodir": "Muhammad + qodir",
    "muhsin": "Yaxshilik qiluvchi, ehsonchi",
    "mukammil": "Mukammal, to'liq yetgan",
    "muqim": "Doimiy, barqaror",
    "murat": "Orzu, istak, tilak (murod varianti)",
    "mustafo": "Tanlangan, saylangan",
    "mustafobe": "Tanlangan + bek",
    "mustafojon": "Tanlangan + jon",
    "murodulloh": "Allohning istagi",
    "muhammadnabi": "Muhammad + payg'ambar",
    "najmiddin": "Dinning yulduzi",
    "nasib": "Nasibali, omadli",
    "nasibulloh": "Allohning nasibasi",
    "nasimjon": "Nasim + jon",
    "nasriddin": "Dinning yordamchisi, g'alabasi",
    "na'mat": "Nemat, in'om, sovg'a",
    "na'matulloh": "Allohning nemati",
    "na'matjon": "Nemat + jon",
    "niyoz": "Tilak, arzu, xizmat",
    "niyozali": "Niyoz + Ali",
    "niyozbek": "Niyoz + bek",
    "niyozjon": "Niyoz + jon",
    "norbek": "Nur + bek",
    "norjon": "Nur + jon",
    "nosir": "Yordamchi, ko'makchi",
    "nufail": "Ko'p, qo'shimcha",
    "nuriddin": "Dinning nuri, yorug'ligi",
    "nurmuhamed": "Nur + Muhammad",
    "nurbek": "Nur + bek",
    "nurjon": "Nur + jon",
    "nuroli": "Nur + Ali",
    "nuroff": "Nur of",
    "obid": "Ibodat qiluvchi",
    "obidbek": "Ibodat qiluvchi + bek",
    "obidjon": "Ibodat qiluvchi + jon",
    "odil": "Adolatli, haqqoniy",
    "odilbek": "Adolatli + bek",
    "odiljon": "Adolatli + jon",
    "olim": "Ilmli, bilimli",
    "olimbek": "Ilmli + bek",
    "olimjon": "Ilmli + jon",
    "olimboy": "Ilmli + boy",
    "omir": "Podsho, boshliq (amir varianti)",
    "orbek": "O'r + bek",
    "orifjon": "Ma'rifatli + jon",
    "orif": "Dono, biluvchi, ma'rifatli",
    "orifbek": "Ma'rifatli + bek",
    "oromjon": "Orom + jon",
    "osim": "Himoyachi, saqlovchi",
    "osman": "Haqiqiy, mustahkam",
    "osmonbek": "Osmon + bek",
    "osmon": "Osmon, samo, yuksak",
    "oxun": "Olima, domla",
    "qahramon": "Qahramon, botir, jasur",
    "qahramonbek": "Qahramon + bek",
    "qahramonjon": "Qahramon + jon",
    "qobil": "Qobiliyatli, qabul qilingan",
    "qobilbek": "Qobiliyatli + bek",
    "qobiljon": "Qobiliyatli + jon",
    "qodir": "Quvvatli, qodir",
    "qodirbek": "Quvvatli + bek",
    "qodirjon": "Quvvatli + jon",
    "qodirali": "Quvvatli + Ali",
    "qo'chqor": "Qo'chqor, kuchli, baquvvat",
    "qo'chqorbek": "Qo'chqor + bek",
    "qo'chqorjon": "Qo'chqor + jon",
    "rahim": "Mehribon, rahmli",
    "rahimjon": "Mehribon + jon",
    "rahimbek": "Mehribon + bek",
    "rahmon": "Mehribon, rahmli (Alloh sifati)",
    "rahmonberdi": "Rahmon + berdi",
    "rahmonbek": "Rahmon + bek",
    "rahmonjon": "Rahmon + jon",
    "rahmatulloh": "Allohning rahmati",
    "rahmatilloh": "Allohning rahmati",
    "rahmatjon": "Rahmat + jon",
    "rahmatbek": "Rahmat + bek",
    "rajabali": "Rajab + Ali",
    "rajabbek": "Rajab + bek",
    "rashid": "To'g'ri yo'ldagi, hidoyatli",
    "rashidbek": "Rashid + bek",
    "rashidjon": "Rashid + jon",
    "ravshan": "Yorqin, ravshan, ochiq",
    "ravshanbek": "Ravshan + bek",
    "ravshanjon": "Ravshan + jon",
    "ravshanali": "Yorqin + Ali",
    "rustam": "Pahlavon, kuchli, afsonaviy qahramon",
    "rustambek": "Rustam + bek",
    "rustamjon": "Rustam + jon",
    "sadriddin": "Dinning sardori",
    "safarali": "Safar + Ali",
    "safarbek": "Safar + bek",
    "sahobiddin": "Sahoba + dinni sevuvchi",
    "salim": "Sog'lom, salomat",
    "salimbek": "Sog'lom + bek",
    "salimjon": "Sog'lom + jon",
    "sardor": "Boshliq, sardor, rahbar",
    "sardorbek": "Boshliq + bek",
    "sardorjon": "Boshliq + jon",
    "sarvar": "Boshliq, rahnamo",
    "sarvarbek": "Boshliq + bek",
    "sarvarjon": "Boshliq + jon",
    "said": "Baxtli, saodatli",
    "saidbek": "Baxtli + bek",
    "saidjon": "Baxtli + jon",
    "saidali": "Baxtli + Ali",
    "samar": "Meva, hosil, natija",
    "samarbek": "Meva + bek",
    "samarjon": "Meva + jon",
    "sami": "Eshituvchi, eshitadigan",
    "samibek": "Eshituvchi + bek",
    "samijon": "Eshituvchi + jon",
    "samir": "Do'st, suhbatdosh",
    "samirbek": "Suhbatdosh + bek",
    "samirjon": "Suhbatdosh + jon",
    "sardor": "Boshliq, rahbar",
    "shahobiddin": "Dinning yulduzi",
    "shahzod": "Shohzoda, qirol o'g'li",
    "shahzodbek": "Shohzoda + bek",
    "shahzodjon": "Shohzoda + jon",
    "sharif": "Sharif, ulug', qadrli",
    "sharifbek": "Sharif + bek",
    "sharifjon": "Sharif + jon",
    "shokir": "Shukr qiluvchi, minnatdor",
    "shokirbek": "Shukr qiluvchi + bek",
    "shokirjon": "Shukr qiluvchi + jon",
    "shuhrat": "Shuhrat, dong, mashhurlik",
    "shuhratbek": "Shuhrat + bek",
    "shuhratjon": "Shuhrat + jon",
    "siddiq": "Haqqoniy, chinchi",
    "siddiqbek": "Haqqoniy + bek",
    "siddiqjon": "Haqqoniy + jon",
    "sohib": "Egasi, sohib, xo'jayin",
    "sohibbek": "Soxib + bek",
    "sohibjon": "Soxib + jon",
    "sohibqiron": "Jahonni zabt etuvchi",
    "sobir": "Sabrli, chidamli",
    "sobirbek": "Sabrli + bek",
    "sobirjon": "Sabrli + jon",
    "sulaymon": "Tinchlik, salomatlik",
    "sulaymonbek": "Sulaymon + bek",
    "sulaymonjon": "Sulaymon + jon",
    "sulton": "Hukmdor, podshoh",
    "sultonbek": "Hukmdor + bek",
    "sultonjon": "Hukmdor + jon",
    "sultonali": "Hukmdor + Ali",
    "tabriz": "Shahar nomi, jasorat",
    "tahir": "Pok, toza, sof",
    "tahirbek": "Pok + bek",
    "tahirjon": "Pok + jon",
    "tal'at": "Chiroyli yuz, husn",
    "tamkin": "Sokin, xotirjam",
    "tohir": "Pok, toza, pokiza",
    "tohirbek": "Pok + bek",
    "tohirjon": "Pok + jon",
    "tojiddin": "Dinning toji",
    "to'lqin": "To'lqin, dengiz to'lqini",
    "to'xtamish": "To'xtagan, tinchlangan",
    "to'qto'g'on": "To'q, to'yingan",
    "to'xtasin": "To'xtab qolsin (omaad tilagi)",
    "tursun": "Tursin, yashasin (omaad tilagi)",
    "tursunali": "Tursin + Ali",
    "tursunboy": "Tursin + boy",
    "tursunbek": "Tursin + bek",
    "tursunjon": "Tursin + jon",
    "ubaydulloh": "Allohning bandasi",
    "umar": "Hayot, umr, uzoq yashovchi",
    "umarali": "Umar + Ali",
    "umarbek": "Umar + bek",
    "umarjon": "Umar + jon",
    "umid": "Umid, istak, orzu",
    "umidjon": "Umid + jon",
    "umidbek": "Umid + bek",
    "umidulloh": "Allohning umidi",
    "urfat": "Ulfat, do'stlik, yaqinlik",
    "urfatbek": "Do'stlik + bek",
    "urfatjon": "Do'stlik + jon",
    "usmon": "Mustahkam, osmon (Usmon varianti)",
    "usmonali": "Usmon + Ali",
    "usmonbek": "Usmon + bek",
    "usmonjon": "Usmon + jon",
    "uxvatulloh": "Allohning tutqichi",
    "vadim": "Kelishuv, va'da",
    "vahidulloh": "Yagona Alloh",
    "vahidjon": "Yagona + jon",
    "vahob": "Berguvchi, in'om etuvchi",
    "vali": "Do'st, avliyo, yaqin",
    "valijon": "Do'st + jon",
    "valibek": "Do'st + bek",
    "vasila": "Vosita, sabab",
    "vohid": "Yagona, bir",
    "vohidjon": "Yagona + jon",
    "vohidbek": "Yagona + bek",
    "vosit": "O'rta, vositachi",
    "xayriddin": "Dinning xayri, yaxshiligi",
    "xayrulloh": "Allohning xayri",
    "xayriddin": "Dinning yaxshiligi",
    "xalil": "Do'st, yaqin, sirdosh",
    "xalilulloh": "Allohning do'sti",
    "xalilbek": "Do'st + bek",
    "xaliljon": "Do'st + jon",
    "xasan": "Yaxshi, go'zal (hasan varianti)",
    "xasanali": "Yaxshi + Ali",
    "xasanbek": "Yaxshi + bek",
    "xasanjon": "Yaxshi + jon",
    "xayrullo": "Allohning xayri",
    "xikmatulloh": "Allohning hikmati",
    "xolmat": "Xolmat, xizmat",
    "xolmirzo": "Xol + mirzo",
    "xolmurod": "Xol + murod",
    "xolbek": "Xol + bek",
    "xomid": "Himoyachi, qo'llab-quvvatlovchi",
    "xurshid": "Quyosh, porloq, yorqin",
    "xurshidbek": "Quyosh + bek",
    "xurshidjon": "Quyosh + jon",
    "xusanboy": "Yaxshi + boy (husan varianti)",
    "xusanjon": "Yaxshi + jon",
    "xudoybergan": "Alloh bergan",
    "xudoyberdi": "Alloh berdi",
    "xudoyshukur": "Allohga shukr",
    "xurram": "Xursand, baxtli, quvonchli",
    "xurrambek": "Xursand + bek",
    "xurramjon": "Xursand + jon",
    "xurshed": "Quyosh (xurshid varianti)",
    "xurshedjon": "Quyosh + jon",
    "yahyo": "Hayot, tiriklik, yashash",
    "yahyobek": "Hayot + bek",
    "yahyojon": "Hayot + jon",
    "yasin": "Qur'on surasi nomi",
    "yokub": "Tutuvchi, almashtiruvchi",
    "yoldosh": "Yo'ldosh, hamroh",
    "yoldoshbek": "Yo'ldosh + bek",
    "yoldoshjon": "Yo'ldosh + jon",
    "yormat": "Yor + mat",
    "yormuhammad": "Yor + Muhammad",
    "yormuhammadali": "Yor + Muhammad + Ali",
    "yormuhammadjon": "Yor + Muhammad + jon",
    "yulbars": "Yo'lbars, jasur, kuchli",
    "yulchiboy": "Yulduz + boy",
    "yulduz": "Yulduz, porloq",
    "yulduzbek": "Yulduz + bek",
    "yulduzjon": "Yulduz + jon",
    "yuldashev": "Yo'ldosh + ev",
    "yuldosh": "Yo'ldosh (yoldosh varianti)",
    "yuldoshali": "Yo'ldosh + Ali",
    "yuldoshbek": "Yo'ldosh + bek",
    "yuldoshjon": "Yo'ldosh + jon",
    "yusuf": "Go'zal, chiroyli, Yusuf payg'ambar",
    "yusufali": "Yusuf + Ali",
    "yusufbek": "Yusuf + bek",
    "yusufjon": "Yusuf + jon",
    "yigitali": "Yigit + Ali",
    "yigitbek": "Yigit + bek",
    "yigitjon": "Yigit + jon",
    "zafar": "G'alaba, zafar, yengish",
    "zafarali": "G'alaba + Ali",
    "zafarbek": "G'alaba + bek",
    "zafarjon": "G'alaba + jon",
    "zakariyo": "Alloh eslab qo'ygan, yod etgan",
    "zamon": "Zamon, davr, vaqt",
    "zamonbek": "Zamon + bek",
    "zamonjon": "Zamon + jon",
    "zohid": "Zohid, dunyodan voz kechgan",
    "zohir": "Zohir, ravshan, ko'rinadigan",
    "zohirbek": "Zohir + bek",
    "zohirjon": "Zohir + jon",
    "zoyir": "Ziyorat qiluvchi, tashrif buyuruvchi",
    "zoyirjon": "Ziyoratchi + jon",
    "zulfikar": "Ikki qirrali qilich, o'tkir",
    "zulfikorbek": "Zulfikar + bek",
    "zulfikarjon": "Zulfikar + jon",
    "ziyodulla": "Allohning ziyosi, ortishi",
    "ziyo": "Nur, yorug'lik, ziyo",
    "ziyobek": "Nur + bek",
    "ziyojon": "Nur + jon",
    "ziyodulla": "Allohning ortishi",
    "ziyoviddin": "Dinning ziysi, nuri",
    "zokir": "Zikr qiluvchi, eslab turuvchi",
    "zokirbek": "Zikr qiluvchi + bek",
    "zokirjon": "Zikr qiluvchi + jon",
    "zohidbek": "Zohid + bek",

    # ===== QIZ ISMLARI =====
    "abdullatif": "Latif Allohning quli",
    "adiba": "Adibli, ma'rifatli, bilimdon",
    "afiza": "Pokiza, toza",
    "afroz": "Porlovchi, yorqin",
    "afsana": "Afsona, hikoya",
    "ag'zam": "Eng ulug', eng buyuk",
    "aida": "Qaytuvchi, qaytib keluvchi",
    "aigul": "Oy go'zali",
    "aisha": "Hayotli, tirik, yashovchi",
    "aigul": "Oy gul",
    "aigerim": "Oy go'zal",
    "aisha": "Hayotli, yashovchi (payg'ambar xotini)",
    "ajar": "Mukofot, savob",
    "ajarniso": "Mukofot + niso",
    "ajiniyaz": "Aji + niyaz",
    "akbota": "Oq bo'ta, oq tuya bolasi",
    "albina": "Oq, oppoq, nurli",
    "alexa": "Himoyachi, yordamchi",
    "alina": "Chiroyli, go'zal, yorqin",
    "alisa": "Aslzoda, yuksak",
    "almira": "Shohzoda, malika",
    "altinoy": "Oltin oy, oltindan qilingan oy",
    "amal": "Umid, orzu, istak",
    "amaliya": "Umidli, orzuli",
    "aminah": "Ishonchli, ishonch bilan (payg'ambar onasi)",
    "amirabonu": "Amir + bonu, podshoh qizi",
    "anisa": "Do'st, sirdosh, yaqin",
    "anorbek": "Anor + bek",
    "anora": "Anor, qizil meva",
    "anjelina": "Farishta, pok",
    "anzirat": "Yulduz, porloq",
    "arzu": "Istak, tilak, orzu",
    "asalgul": "Asal + gul, shirin gul",
    "asaloy": "Asal + oy, shirin oy",
    "asena": "Bo'ri, turkiy afsonaviy ona",
    "asima": "Himoyalangan, saqlangan",
    "asiya": "Ko'taruvchi, yuksak (Fir'avn xotini)",
    "asma": "Oliy, yuksak, baland",
    "asomiddin": "Dinning himoyachisi",
    "atirgul": "Atir + gul, hidli gul",
    "aisha": "Hayotli, yashovchi",
    "aziza": "Qadrli, hurmatli, aziz",
    "azizabonu": "Aziz + bonu",
    "bahora": "Bahor fasli, bahorgul",
    "bahri": "Dengiz, keng",
    "baxora": "Xushbo'y hid, bahora gul",
    "baxti": "Baxt, omad",
    "baxtigul": "Baxt + gul",
    "baxtiniso": "Baxt + niso",
    "baxtiyar": "Baxtli (erkak/qiz)",
    "barno": "Yosh, yigitlik (qiz varianti)",
    "barnoy": "Yosh + oy",
    "begoyim": "Beka + oyim",
    "behira": "Dengiz, ulkan",
    "belqis": "Malika, Saba malikasi",
    "benafsha": "Binafsha guli",
    "bibi": "Xonim, ayol, ona",
    "bibisora": "Bibi + sora",
    "bibiaysha": "Bibi + Aisha",
    "bibifotima": "Bibi + Fotima",
    "bibihamdam": "Bibi + hamdam",
    "binoyi": "Binoyi, go'zal",
    "biyroniso": "Biyron + niso",
    "bostangul": "Bostan + gul",
    "boychechak": "Boy + chechak",
    "bojialik": "Boji + lik",
    "buxor": "Buxoro shahri",
    "dildora": "Dil sohibi, sevgan",
    "dildorabonu": "Dil sohibi + bonu",
    "dilorom": "Dil + orom, ko'ngil tinchligi",
    "dilrabo": "Dil + rabo, dilni o'g'irlagan",
    "dilfuza": "Dil + fuza, ko'ngilni egallagan",
    "dilnoza": "Dil + noza, dilni bezagan",
    "dilnora": "Dil + nora, dilni yoritgan",
    "dilshoda": "Ko'ngli xursand, shod (erkak: dilshod)",
    "dinora": "Oltin tanga, qiymatli",
    "durdona": "Durr + dona, marvarid",
    "durdonabonu": "Durdona + bonu",
    "durdona": "Marvarid, qimmatbaho",
    "durro": "Marvarid",
    "durronisa": "Durr + nisa, marvarid ayol",
    "durroniso": "Marvarid ayol",
    "edilar": "Sevgi, muhabbat",
    "eglina": "Nurli, yorqin",
    "ekaterina": "Pokiza, toza",
    "elgun": "El quyoshi",
    "elnora": "El + nora",
    "elnoza": "El + noza",
    "elshoda": "El + shoda, elni xursand qilgan",
    "elona": "El ona, elning onasi",
    "elzoda": "El + zoda, elning qizi",
    "elyora": "El + yora",
    "emiliya": "Raqobatbardosh, mehnatkash",
    "erika": "Mangu hukmdor",
    "esabella": "Allohga qasam ichgan",
    "farangiz": "Farang + giz, dunyoga mashhur",
    "farida": "Yagona, beqiyos, noyob",
    "farizoda": "Farzand, qiz, nozik",
    "fariha": "Xursand, quvnoq, xushhol",
    "farrux": "Baxtli, yuzi yorqin (erkak/qiz)",
    "fayruza": "Fayruza, yashil tosh",
    "fayruza": "Fayruza toshi",
    "fotima": "Sutdan ajratgan, pokiza (payg'ambar qizi)",
    "fotimabonu": "Fotima + bonu",
    "fotimasulton": "Fotima + sulton",
    "fotimahon": "Fotima + hon",
    "fotimahonim": "Fotima + honim",
    "furqat": "Ajralish, ayriliq (erkak/qiz)",
    "galina": "Tinch, osoyishta",
    "gul": "Gul, guldasta",
    "gulanda": "Gul + anda",
    "gulara": "Gul + ara",
    "gulbahor": "Gul + bahor",
    "gulbahor": "Bahor guli",
    "gulchehra": "Gul + chehra, gul yuzli",
    "gulchexra": "Gul yuzli",
    "gulchin": "Gul + chin, guldasta",
    "gulchinoy": "Gulchin + oy",
    "gulchechak": "Gul + chechak",
    "gulda": "Gul + da",
    "guldasta": "Gul dastasi, guldasta",
    "gule": "Gul, guldasta (kurdlacha)",
    "gulefson": "Gul + afsun",
    "gulendom": "Gul + endom, gul qaddi",
    "gulfira": "Gul + fira",
    "gulhayo": "Gul + hayo",
    "gulirano": "Gul + irano",
    "guljamol": "Gul + jamol, gul go'zallik",
    "guljan": "Gul + jan",
    "guljahon": "Gul + jahon",
    "gulnara": "Gul + nora, gullardan yorqin",
    "gulnora": "Gul + nora, gul yorug'lik",
    "gulnoza": "Gul + noza, gul bezagi",
    "gulniso": "Gul + niso, gullar ayoli",
    "gulsara": "Gul + sara",
    "gulsum": "Qisqa sochli, go'zal",
    "gultola": "Gul + tola",
    "gulxanoy": "Gul + xanoy",
    "gulxora": "Gul + xora",
    "gulzoda": "Gul + zoda, gul kabi qiz",
    "gulzora": "Gulzor + a, gul bog'i",
    "halima": "Sabrli, muloyim (payg'ambar onasi)",
    "halimabonu": "Halima + bonu",
    "hamida": "Maqtovga loyiq, maqtalgan",
    "hamida": "Maqtalgan ayol",
    "hanna": "Xudo in'om etgan",
    "hayot": "Hayot, tiriklik, yashash",
    "hayotxon": "Hayot + xon",
    "hazon": "Xazon, kuz bargi",
    "hijron": "Ayriliq, hijron",
    "hilola": "Yangi oy, hilol oy",
    "hoshim": "Non ushatuvchi (erkak/qiz)",
    "husniya": "Husnli, go'zal",
    "ibrat": "Sabab, ibrat, o'rnak",
    "ifor": "Xushbo'y hid, atir",
    "ildana": "Ilhom, ilhomlantiruvchi",
    "ilhom": "Ilhom, ruh bag'ishlash",
    "ilodabonu": "Iloda + bonu",
    "ilona": "Yorug'lik, nur",
    "ilvira": "Yordamchi, himoyachi",
    "iman": "Imon, ishonch",
    "imona": "Imonli, ishongan",
    "inoyat": "Inoyat, lutf, mehribonlik",
    "inoyatbeka": "Inoyat + beka",
    "insof": "Insof, adolat, vijdon",
    "iqbol": "Omad, baxt, farovonlik",
    "irada": "Iroda, ixtiyor, xohish",
    "iroda": "Iroda, mustaqillik, kuchli xohish",
    "isfandiyar": "Pak, toza (erkak/qiz)",
    "jannat": "Jannat, behisht, bog'",
    "jannatgul": "Jannat + gul",
    "jahon": "Dunyo, olam, jahon",
    "jahona": "Dunyo ayoli, jahon ayoli",
    "jahonara": "Dunyoni bezagan",
    "jahongul": "Jahon + gul",
    "jahonniso": "Dunyo + nisa",
    "jahonor": "Dunyo + or, dunyoni sharafli qilgan",
    "jamilya": "Go'zal, chiroyli, husnli",
    "jamola": "Go'zallik, husn",
    "jamoliddin": "Dinning go'zalligi (erkak/qiz)",
    "janobibonu": "Janobi + bonu",
    "jasmina": "Yasemin guli",
    "jasmin": "Yasemin, xushbo'y gul",
    "jasmira": "Yasmin + ira",
    "jiguloy": "Jiguli + oy",
    "jigul": "Jiguli tog'lari",
    "jodira": "Jodugar, sehrli",
    "jumanazar": "Juma + nazar",
    "jumagul": "Juma + gul",
    "jupagul": "Jupa + gul",
    "kamala": "Kamolga yetgan",
    "kamola": "Kamolga yetgan, mukammal ayol",
    "karima": "Saxiy, karamli, mehribon",
    "keksa": "Katta, ulug'",
    "keyla": "Kalit, hal qiluvchi",
    "kimyo": "Kimyo, sirli narsa",
    "kobra": "Katta, ulug'",
    "konsiya": "Xazinachi, saqlovchi",
    "kosima": "Gul, go'zal",
    "kubaro": "Katta, yuksak",
    "kumushoy": "Kumush + oy",
    "kumush": "Kumush, oq metall",
    "kumushbek": "Kumush + bek",
    "kumushjon": "Kumush + jon",
    "lalezar": "Lola bog'i, lola zori",
    "latifabonu": "Latifa + bonu",
    "latifa": "Nozik, nafis, yumshoq",
    "laylo": "Tun, kecha (Layli va Majnun)",
    "laylo": "Tun, qorong'u kecha",
    "lenora": "Nurli, yorqin",
    "leyli": "Tun, kecha",
    "lilya": "Lola gul, nilufar",
    "lobar": "Katta, ulug'",
    "lola": "Lola guli, qizil gul",
    "lolabonu": "Lola + bonu",
    "lola": "Lola guli",
    "lolaxon": "Lola + xon",
    "lolaoy": "Lola + oy",
    "lubna": "Xushbo'y daraxt",
    "luqmon": "Hakim, donishmand (erkak)",
    "lyubov": "Sevgi, muhabbat",
    "madina": "Madina shahri, pok shahar",
    "madinabonu": "Madina + bonu",
    "mahbuba": "Sevilgan, suyukli",
    "mahfuza": "Himoyalangan, saqlangan",
    "mahliqo": "Oy yuzli, go'zal",
    "mahliqobonu": "Mahliqo + bonu",
    "mahliqohon": "Mahliqo + hon",
    "mahliqoxon": "Mahliqo + xon",
    "mahzuna": "G'amgin, mahzun (foydalanilmaydi)",
    "malak": "Farishta, pok",
    "malikabonu": "Malika + bonu",
    "malika": "Malika, shoh qizi",
    "malikaxon": "Malika + xon",
    "marguba": "Sevilgan, suyukli",
    "marg'uba": "Sevilgan, ardoqlangan",
    "mariya": "Maryam, pokiza (erkak/qiz variantlari bor)",
    "mariyam": "Maryam, pokiza, toza",
    "marjona": "Marjon, qizil tosh",
    "marufabonu": "Marufa + bonu",
    "marufabonu": "Marufa + bonu",
    "marufa": "Yaxshi, ma'lum, tanilgan",
    "marxabo": "Marhabo, salom",
    "marjamat": "Marhamat, rahm-shafqat",
    "matluba": "Istak, tilak, orzu",
    "mayram": "Mayram, bayram",
    "mayramgul": "Bayram + gul",
    "mayruniso": "Mayrun + nisa",
    "mehmonabonu": "Mehmon + bonu",
    "mehrigul": "Mehribon + gul",
    "mehrinoz": "Mehribon + noz",
    "mehribo": "Mehribon",
    "mehribon": "Mehribon, shafqatli (erkak/qiz)",
    "mehrijon": "Mehribon + jon",
    "mehrniso": "Mehribon + nisa",
    "mehro": "Mehribon + o",
    "mehtargul": "Mehtar + gul",
    "meruert": "Marvarid, qimmatbaho (qozoqcha)",
    "minnora": "Minora, baland bino",
    "minora": "Masjid minorasi",
    "mo'g'ul": "Mo'g'ul qizi",
    "mo'g'ulon": "Mo'g'ul on",
    "mo'g'uloy": "Mo'g'ul oy",
    "mo'g'ulbonu": "Mo'g'ul + bonu",
    "mo'g'ulxon": "Mo'g'ul + xon",
    "mo'g'ulzoda": "Mo'g'ul + zoda",
    "mohtab": "Oy nuri, oy yorug'ligi",
    "mojida": "Ulug', buyuk",
    "mojigul": "Moji + gul",
    "monabonu": "Mona + bonu",
    "monagul": "Mona + gul",
    "munavvar": "Yorqin, nurli, porloq",
    "munavvarbonu": "Munavvar + bonu",
    "munisa": "Sirdosh, do'st, suhbatdosh",
    "munojot": "Duo, iltijo, yolvorish",
    "munira": "Yorqin, porloq, nurli",
    "muradxon": "Murod + xon",
    "muslima": "Musulmon ayol, tinchlik sohibasi",
    "muqaddas": "Muqaddas, pok, muqaddas",
    "muqaddasbonu": "Muqaddas + bonu",
    "muqimabonu": "Muqima + bonu",
    "muqima": "Doimiy, barqaror",
    "murshida": "Yo'l ko'rsatuvchi, rahbar",
    "muslima": "Musulmon, tinchlik sohibasi",
    "mutriba": "Musiqa, qo'shiq aytuvchi",
    "muzaffarabonu": "Muzaffara + bonu",
    "muyassar": "Oson, qulay, muyassar",
    "nargiza": "Nargiz guli",
    "nargizabonu": "Nargiza + bonu",
    "nargizxon": "Nargiz + xon",
    "narjis": "Nargiz guli, xushbo'y gul",
    "nasiba": "Nasibali, omadli",
    "nasibabonu": "Nasiba + bonu",
    "nasibaxon": "Nasiba + xon",
    "nasyba": "Nasiba varianti",
    "nasiba": "Nasibali, omadli",
    "nasima": "Nasim, shabada, yengil shamol",
    "nasira": "Yordamchi, g'olib",
    "nayli": "Nayli, musiqiy",
    "nazabonu": "Naza + bonu",
    "nazakabonu": "Nazakatli + bonu",
    "nazakat": "Nazokat, noziklik, nafosat",
    "nazakabonu": "Nazakat + bonu",
    "nazanin": "Nozik, nafis, go'zal",
    "nazira": "Andoza, namuna",
    "nazokat": "Nazokat, noziklik",
    "nazokatbonu": "Nazokat + bonu",
    "nazoxon": "Naza + xon",
    "nazrin": "Narin, nozik, xushbo'y gul",
    "nazrinoy": "Nazrin + oy",
    "nazokat": "Nazokat, noziklik",
    "nazoxonim": "Naza + xonim",
    "nazgul": "Naza + gul",
    "nazira": "Andoza, namuna",
    "nazli": "Nozik, nazokatli",
    "nazokat": "Nazokat, noziklik",
    "nazi": "Naza, nozik",
    "nigora": "Rasm, surat",
    "nigorabonu": "Nigora + bonu",
    "nigora": "Rasm, surat, go'zal",
    "nigorabonu": "Nigora + bonu",
    "nigora": "Rasm, surat, go'zal qiz",
    "nigoraxon": "Nigora + xon",
    "nigora": "Rasm, surat",
    "nigora": "Go'zal, chiroyli",
    "nigora": "Rasm, surat",
    "nigora": "Chiroyli qiz",
    "nilufar": "Nilufar guli, suv guli",
    "nilufarbomu": "Nilufar + bonu",
    "nilufaron": "Nilufar + on",
    "nilufarxon": "Nilufar + xon",
    "nilufarbeka": "Nilufar + beka",
    "nodira": "Noyob, beqiyos, yagona",
    "nodirabonu": "Nodira + bonu",
    "nodiraxon": "Nodira + xon",
    "nora": "Nur, yorug'lik, porloq",
    "norabonu": "Nora + bonu",
    "noraxon": "Nora + xon",
    "nozanin": "Nozik, nafis, go'zal",
    "noza": "Noz, erkalik",
    "nozabonu": "Naza + bonu",
    "nozakat": "Nazokat, noziklik",
    "nozik": "Nozik, ingichka",
    "nozanin": "Nozik, nafis",
    "nozani": "Nozik, go'zal",
    "noza": "Noz, erkalik",
    "nozanin": "Nozik, nafis, go'zal",
    "nozigul": "Nozik + gul",
    "nozanin": "Nozik, nafis",
    "nozikbonu": "Nozik + bonu",
    "nurbeka": "Nur + beka",
    "nurbibi": "Nur + bibi",
    "nurbibi": "Nurli xonim",
    "nurbonu": "Nur + bonu",
    "nurga": "Nur + ga",
    "nurgul": "Nur + gul",
    "nurigul": "Nur + gul",
    "nuribonu": "Nuri + bonu",
    "nurijon": "Nuri + jon",
    "nurixon": "Nuri + xon",
    "nurlanay": "Nurlan + ay",
    "nurali": "Nur + Ali",
    "nursulpan": "Nur + sulpan",
    "nursulpan": "Nurli sochli",
    "nurzoda": "Nur + zoda, nurli qiz",
    "nurziya": "Nur + ziya",
    "nurbay": "Nur + bay",
    "nurbonu": "Nur + bonu",
    "nurzhamal": "Nur + jamol",
    "nurjahon": "Nur + jahon",
    "nurniso": "Nur + nisa",
    "nuroy": "Nur + oy",
    "nurxan": "Nur + xon",
    "nurbala": "Nur + bola",
    "nurjamol": "Nur + jamol",
    "nurxon": "Nur + xon",
    "nurxonim": "Nur + xonim",
    "nurziyo": "Nur + ziyo",
    "oybibi": "Oy + bibi",
    "oychehra": "Oy + chehra, oy yuzli",
    "oygul": "Oy + gul",
    "oyguloy": "Oygul + oy",
    "oydin": "Yorqin, ravshan, aydin",
    "oydina": "Yorqin ayol, nurli",
    "oygul": "Oy + gul, oy guli",
    "oyguloy": "Oygul + oy",
    "oyim": "Oyim, xonim, ona",
    "oyimbonu": "Oyim + bonu",
    "oyimoy": "Oyim + oy",
    "oyinoy": "Oyi + noy",
    "oyjan": "Oy + jan",
    "oygul": "Oy guli",
    "oygulbonu": "Oygul + bonu",
    "oygulxon": "Oygul + xon",
    "oydinoy": "Oydin + oy",
    "oygul": "Oy guli",
    "oygulbonu": "Oy gul bonu",
    "oygulxon": "Oy gul xon",
    "oygul": "Oy guli",
    "oygulbonu": "Oy gul bonu",
    "oygulxon": "Oy gul xon",
    "oygul": "Oy guli",
    "oygulbonu": "Oy gul bonu",
    "oygulxon": "Oy gul xon",
    "oygul": "Oy guli",
    "oygulbonu": "Oy gul bonu",
    "oygulxon": "Oy gul xon",
    "oygul": "Oy guli",
    "oygulbonu": "Oy gul bonu",
    "oygulxon": "Oy gul xon",
    "oyimoy": "Oyim oy",
    "oyimxon": "Oyim + xon",
    "oyim": "Xonim, ona",
    "oyimbonu": "Oyim bonu",
    "oyimoy": "Oyim oy",
    "oyinabonu": "Oyina + bonu",
    "oyina": "Ko'zgu, aks ettiruvchi",
    "oyisha": "Hayotli (aisha varianti)",
    "oyjan": "Oy + jan",
    "oygulbonu": "Oy gul bonu",
    "oygul": "Oy guli",
    "oygulbonu": "Oy gul bonu",
    "oygulxon": "Oy gul xon",
    "oyim": "Xonim, ona",
    "oyimbonu": "Oyim bonu",
    "oyimoy": "Oyim oy",
    "oyimxon": "Oyim xon",
    "oyinabonu": "Oyina bonu",
    "oyina": "Ko'zgu, aks",
    "oyisha": "Hayotli",
    "oyjan": "Oy jan",
    "oysha": "Hayotli (aisha varianti)",
    "parizoda": "Parizoda, pari qizi",
    "parizod": "Pari qizi",
    "parizoda": "Pari zoda, pari qizi",
    "parizodabonu": "Parizoda + bonu",
    "parizodxon": "Parizoda + xon",
    "parizod": "Pari zoda",
    "pari": "Pari, afsonaviy mavjudot",
    "parizoda": "Pari qizi",
    "parizodabonu": "Parizoda bonu",
    "parizodxon": "Parizoda xon",
    "parvina": "Plevada yulduzi",
    "parvin": "Yulduz, plevada",
    "parvina": "Plevada yulduzi",
    "payastabonu": "Payasta + bonu",
    "pirova": "Birinchi, oldingi",
    "pokiza": "Pok, toza, sof",
    "pokizabonu": "Pokiza + bonu",
    "pokizaxon": "Pokiza + xon",
    "ra'no": "Nozik, go'zal, nafis",
    "ra'nobonu": "Ra'no + bonu",
    "ra'noxon": "Ra'no + xon",
    "rabiya": "Bahor, to'rtinchi (ayol valiy)",
    "rabia": "Bahor, to'rtinchi",
    "rahima": "Mehribon, rahmli",
    "rahimabonu": "Rahima + bonu",
    "rahimaxon": "Rahima + xon",
    "rahmatbeka": "Rahmat + beka",
    "rahmatbonu": "Rahmat + bonu",
    "rahmatxon": "Rahmat + xon",
    "rafiqabonu": "Rafiqa + bonu",
    "rafiqa": "Hamroh, do'st, rafiq",
    "raziya": "Rozilik, qanoat, mamnun",
    "raziyabonu": "Raziya + bonu",
    "raziyaxon": "Raziya + xon",
    "robia": "Bahor, to'rtinchi (rabiya varianti)",
    "ruhimabonu": "Ruhima + bonu",
    "ruhimaxon": "Ruhima + xon",
    "ruqiyabonu": "Ruqiya + bonu",
    "ruqiya": "Yuksalish, ko'tarilish",
    "rushana": "Yorqin, ravshan",
    "rushanabonu": "Rushana + bonu",
    "rushanaxon": "Rushana + xon",
    "sabina": "Sabina, sabrli",
    "sabohat": "Go'zallik, husn, chiroy",
    "sabohatbonu": "Sabohat + bonu",
    "sabohatxon": "Sabohat + xon",
    "sabira": "Sabrli, chidamli",
    "sabirabonu": "Sabira + bonu",
    "sabiraxon": "Sabira + xon",
    "sahlo": "Oson, qulay",
    "saidabonu": "Saida + bonu",
    "saidaxon": "Saida + xon",
    "saida": "Baxtli, saodatli (erkak/qiz)",
    "saidabonu": "Saida + bonu",
    "saidaxon": "Saida + xon",
    "sakhina": "Issiq, qizg'in",
    "sakina": "Tinchlik, osoyishtalik",
    "salmabonu": "Salma + bonu",
    "salmaxon": "Salma + xon",
    "salmabonu": "Salma + bonu",
    "salmaxon": "Salma + xon",
    "salma": "Tinch, osoyishta",
    "salmabonu": "Salma bonu",
    "salmahon": "Salma hon",
    "salmaxon": "Salma xon",
    "salmabonu": "Salma bonu",
    "salmahon": "Salma hon",
    "salmabonu": "Salma bonu",
    "salmahon": "Salma hon",
    "salmabonu": "Salma bonu",
    "salmahon": "Salma hon",
    "salmabonu": "Salma bonu",
    "salmahon": "Salma hon",
    "saltanat": "Saltanat, hukmronlik",
    "samabonu": "Sama + bonu",
    "samaxon": "Sama + xon",
    "samara": "Meva, hosil, natija",
    "samarabonu": "Samara + bonu",
    "samaraxon": "Samara + xon",
    "samara": "Meva, hosil",
    "samirabonu": "Samira + bonu",
    "samiraxona": "Samira + xona",
    "samira": "Do'st, suhbatdosh (erkak/qiz)",
    "samirabonu": "Samira bonu",
    "samiraxona": "Samira xona",
    "samara": "Meva, hosil",
    "samirabonu": "Samira bonu",
    "samiraxona": "Samira xona",
    "samira": "Suhbatdosh, do'st",
    "samirabonu": "Samira bonu",
    "samiraxona": "Samira xona",
    "samoyabonu": "Samoya + bonu",
    "samoyaxon": "Samoya + xon",
    "sanam": "Sanam, go'zal, but",
    "sanambonu": "Sanam + bonu",
    "sanamxon": "Sanam + xon",
    "sara": "Sara, toza, pok",
    "sarabonu": "Sara + bonu",
    "saraxon": "Sara + xon",
    "sarvinaz": "Sarv + naz, sarv qaddi nozli",
    "sarvinazbonu": "Sarvinaz + bonu",
    "sarvinazxon": "Sarvinaz + xon",
    "sitora": "Yulduz, yulduzcha",
    "sitorabonu": "Sitora + bonu",
    "sitoraxon": "Sitora + xon",
    "sofina": "Kema, safina",
    "sofinabonu": "Sofina + bonu",
    "sofinaxon": "Sofina + xon",
    "sofia": "Donolik, hikmat",
    "sohibabonu": "Sohiba + bonu",
    "sohibaxon": "Sohiba + xon",
    "sohiba": "Egasi, sohib, xo'jayin ayol",
    "sohibabonu": "Sohiba bonu",
    "sohibaxon": "Sohiba xon",
    "soliha": "Yaxshi, solih, taqvodor",
    "soliha": "Yaxshi, taqvodor ayol",
    "solihabonu": "Soliha + bonu",
    "solihaxon": "Soliha + xon",
    "soriya": "Yulduz, porloq",
    "sorabonu": "Sora + bonu",
    "soraxon": "Sora + xon",
    "sitora": "Yulduz",
    "sitorabonu": "Sitora bonu",
    "sitoraxon": "Sitora xon",
    "subhonabonu": "Subhona + bonu",
    "subhonaxon": "Subhona + xon",
    "subhona": "Pokiza, toza",
    "subhonabonu": "Subhona bonu",
    "subhonaxon": "Subhona xon",
    "sultana": "Sulton ayol",
    "sultonabonu": "Sultona + bonu",
    "sultonoy": "Sulton + oy",
    "sultaxon": "Sulton + xon",
    "sultonbonu": "Sulton + bonu",
    "sumaya": "Baland, yuksak",
    "sumayabonu": "Sumaya + bonu",
    "sumayaxon": "Sumaya + xon",
    "sumayya": "Baland, yuksak (sahobiy ayol)",
    "surayyo": "Yulduzlar to'dasi, plevada",
    "surayyobonu": "Surayyo + bonu",
    "surayyoxon": "Surayyo + xon",
    "suvora": "Chiroyli, go'zal",
    "suvorabonu": "Suvora + bonu",
    "suvoraxon": "Suvora + xon",
    "tamarabonu": "Tamara + bonu",
    "tamaraxon": "Tamara + xon",
    "tamara": "Xurmo daraxti",
    "tamarabonu": "Tamara bonu",
    "tamaraxon": "Tamara xon",
    "tansari": "Tan + sari",
    "tanabonu": "Tana + bonu",
    "taninoy": "Tani + noy",
    "tazabonu": "Taza + bonu",
    "tazaxon": "Taza + xon",
    "tuhfa": "Sovg'a, hadya, in'om",
    "tuhfabonu": "Tuhfa + bonu",
    "tuhfaxon": "Tuhfa + xon",
    "tursunoy": "Tursin + oy",
    "ubaydabonu": "Ubayda + bonu",
    "ubaydaxon": "Ubayda + xon",
    "ugiloy": "Qiz + oy",
    "ulmasabonu": "Ulmasa + bonu",
    "ulmasaxon": "Ulmasa + xon",
    "ulmasa": "O'lmas, abadiy",
    "ulmasabonu": "Ulmasa bonu",
    "ulmasaxon": "Ulmasa xon",
    "umidabonu": "Umida + bonu",
    "umidaxon": "Umida + xon",
    "umida": "Umidli, orzuli",
    "umidabonu": "Umida bonu",
    "umidaxon": "Umida xon",
    "uzbeka": "O'zbek ayol",
    "valentina": "Sog'lom, kuchli",
    "vasila": "Vosita, sabab (erkak/qiz)",
    "vazirabonu": "Vazira + bonu",
    "vaziraxon": "Vazira + xon",
    "vazira": "Vazir, maslahatchi ayol",
    "vazirabonu": "Vazira bonu",
    "vaziraxon": "Vazira xon",
    "vazira": "Maslahatchi ayol",
    "vazirabonu": "Vazira bonu",
    "vaziraxon": "Vazira xon",
    "viktoriya": "G'alaba, zafar",
    "violetta": "Binafsha gul",
    "xadija": "Vaqti oldin tug'ilgan (payg'ambar birinchi xotini)",
    "xadichabonu": "Xadija + bonu",
    "xadichaxon": "Xadija + xon",
    "xairabonu": "Xaira + bonu",
    "xairabonu": "Xayirli + bonu",
    "xairaxon": "Xaira + xon",
    "xaira": "Xayirli, yaxshi",
    "xairabonu": "Xaira bonu",
    "xairaxon": "Xaira xon",
    "xalimabonu": "Xalima + bonu",
    "xalimaxon": "Xalima + xon",
    "xayrbonu": "Xayr + bonu",
    "xayrxon": "Xayr + xon",
    "xayriniso": "Xayr + niso",
    "xayrunniso": "Xayr + nisa, xayrli ayol",
    "xayot": "Hayot (variant)",
    "xayotxon": "Hayot + xon",
    "xayriniso": "Xayrli niso",
    "xayrunniso": "Xayrli ayol",
    "xayot": "Hayot, tiriklik",
    "xayotxon": "Hayot + xon",
    "xayriniso": "Xayrli ayol",
    "xayrunniso": "Xayrli ayol",
    "xayot": "Hayot, tiriklik",
    "xayotxon": "Hayot + xon",
    "xayriniso": "Xayrli ayol",
    "xayrunniso": "Xayrli ayol",
    "xolida": "Abadiy, doimiy",
    "xolidabonu": "Xolida + bonu",
    "xolidaxon": "Xolida + xon",
    "xolida": "Abadiy, doimiy",
    "xolidabonu": "Xolida bonu",
    "xolidaxon": "Xolida xon",
    "xolida": "Abadiy",
    "xolidabonu": "Xolida bonu",
    "xolidaxon": "Xolida xon",
    "xolida": "Abadiy",
    "xolidabonu": "Xolida bonu",
    "xolidaxon": "Xolida xon",
    "xosiyat": "Foyda, foydali, sifat",
    "xosiyatbonu": "Xosiyat + bonu",
    "xosiyatxon": "Xosiyat + xon",
    "xosiyat": "Foyda, sifat",
    "xosiyatbonu": "Xosiyat bonu",
    "xosiyatxon": "Xosiyat xon",
    "xosiyat": "Foyda, sifat",
    "xosiyatbonu": "Xosiyat bonu",
    "xosiyatxon": "Xosiyat xon",
    "xubayda": "Kichkina, yoqimli",
    "xubaydabonu": "Xubayda + bonu",
    "xubaydaxon": "Xubayda + xon",
    "xumoyun": "Baxtli, muqaddas, baxt qushi",
    "xumorabonu": "Xumora + bonu",
    "xumoraxon": "Xumora + xon",
    "xumora": "Xumor, istak",
    "xumorabonu": "Xumora bonu",
    "xumoraxon": "Xumora xon",
    "xumorabonu": "Xumora bonu",
    "xumoraxon": "Xumora xon",
    "xumorabonu": "Xumora bonu",
    "xumoraxon": "Xumora xon",
    "xumorabonu": "Xumora bonu",
    "xumoraxon": "Xumora xon",
    "xumorabonu": "Xumora bonu",
    "xumoraxon": "Xumora xon",
    "xumorabonu": "Xumora bonu",
    "xumoraxon": "Xumora xon",
    "xumorabonu": "Xumora bonu",
    "xumoraxon": "Xumora xon",
    "xumorabonu": "Xumora bonu",
    "xumoraxon": "Xumora xon",
    "xuraman": "Xurram, baxtli",
    "xuramabonu": "Xurama + bonu",
    "xuramaxon": "Xurama + xon",
    "xuraman": "Xurram, baxtli",
    "xuramabonu": "Xurama bonu",
    "xuramaxon": "Xurama xon",
    "xuramabonu": "Xurama bonu",
    "xuramaxon": "Xurama xon",
    "xuramabonu": "Xurama bonu",
    "xuramaxon": "Xurama xon",
    "xuramabonu": "Xurama bonu",
    "xuramaxon": "Xurama xon",
    "xuramabonu": "Xurama bonu",
    "xuramaxon": "Xurama xon",
    "xuraman": "Baxtli, xursand",
    "xuramabonu": "Xurama bonu",
    "xuramaxon": "Xurama xon",
    "xuraman": "Baxtli",
    "xuramabonu": "Xurama bonu",
    "xuramaxon": "Xurama xon",
    "xurshida": "Quyosh, porloq (xurshid qiz varianti)",
    "xurshidabonu": "Xurshida + bonu",
    "xurshidaxon": "Xurshida + xon",
    "xurshidabonu": "Xurshida bonu",
    "xurshidaxon": "Xurshida xon",
    "xurshidabonu": "Xurshida bonu",
    "xurshidaxon": "Xurshida xon",
    "yasamina": "Yasemin guli",
    "yasmin": "Yasemin guli",
    "yasminabonu": "Yasmina + bonu",
    "yasminaxon": "Yasmina + xon",
    "yulduz": "Yulduz (erkak/qiz)",
    "yulduzbonu": "Yulduz + bonu",
    "yulduzxon": "Yulduz + xon",
    "yulduzoy": "Yulduz + oy",
    "yulduzbonu": "Yulduz bonu",
    "yulduzxon": "Yulduz xon",
    "yulduzoy": "Yulduz oy",
    "yulduzbonu": "Yulduz bonu",
    "yulduzxon": "Yulduz xon",
    "yulduzbonu": "Yulduz bonu",
    "yulduzxon": "Yulduz xon",
    "yulduzbonu": "Yulduz bonu",
    "yulduzxon": "Yulduz xon",
    "yumabonu": "Yuma + bonu",
    "yumaxon": "Yuma + xon",
    "yulduz": "Yulduz",
    "yulduzbonu": "Yulduz bonu",
    "yulduzxon": "Yulduz xon",
    "yulduzbonu": "Yulduz bonu",
    "yulduzxon": "Yulduz xon",
    "yulduzoy": "Yulduz oy",
    "yulduz": "Yulduz, porloq",
    "yulduzbonu": "Yulduz + bonu",
    "yulduzxon": "Yulduz + xon",
    "yulduzbonu": "Yulduz bonu",
    "yulduzxon": "Yulduz xon",
    "yulduzbonu": "Yulduz bonu",
    "yulduzxon": "Yulduz xon",
    "yulduzbonu": "Yulduz bonu",
    "yulduzxon": "Yulduz xon",
    "zabira": "Kuchli, quvvatli",
    "zabirabonu": "Zabira + bonu",
    "zabiraxon": "Zabira + xon",
    "zahra": "Yorqin, porloq, gul (Fotima Zahra)",
    "zahrabonu": "Zahra + bonu",
    "zahraxon": "Zahra + xon",
    "zahirabonu": "Zahira + bonu",
    "zahiraxon": "Zahira + xon",
    "zahra": "Yorqin, gul",
    "zahrabonu": "Zahra bonu",
    "zahraxon": "Zahra xon",
    "zahrabonu": "Zahra bonu",
    "zahraxon": "Zahra xon",
    "zahrabonu": "Zahra bonu",
    "zahraxon": "Zahra xon",
    "zahrabonu": "Zahra bonu",
    "zahraxon": "Zahra xon",
    "zahrabonu": "Zahra bonu",
    "zahraxon": "Zahra xon",
    "zainab": "Otaning bezagi (payg'ambar qizi)",
    "zaynab": "Ota bezagi, chiroyli (zainab varianti)",
    "zaynabbonu": "Zaynab + bonu",
    "zaynabxon": "Zaynab + xon",
    "zaynab": "Chiroyli, otaning bezagi",
    "zaynabbonu": "Zaynab bonu",
    "zaynabxon": "Zaynab xon",
    "zaynabbonu": "Zaynab bonu",
    "zaynabxon": "Zaynab xon",
    "zaynab": "Chiroyli",
    "zaynabbonu": "Zaynab bonu",
    "zaynabxon": "Zaynab xon",
    "zaynabbonu": "Zaynab bonu",
    "zaynabxon": "Zaynab xon",
    "zaynabbonu": "Zaynab bonu",
    "zaynabxon": "Zaynab xon",
    "zaynabbonu": "Zaynab bonu",
    "zaynabxon": "Zaynab xon",
    "zafarabonu": "Zafara + bonu",
    "zafaraxon": "Zafara + xon",
    "zamira": "Yurak, qalb, vijdon",
    "zamilabonu": "Zamila + bonu",
    "zamilaxon": "Zamila + xon",
    "zamira": "Vijdon, yurak",
    "zamirabonu": "Zamira + bonu",
    "zamiraxon": "Zamira + xon",
    "zamira": "Vijdon, yurak",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamira": "Vijdon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamira": "Yurak, vijdon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
    "zamiraxon": "Zamira xon",
    "zamirabonu": "Zamira bonu",
}



# ═══════════════════════════════════════════════════════════
#  ISMLAR MA'NOSI — KENG KAMUS (500+ ISM)
# ═══════════════════════════════════════════════════════════
ISMLAR = {
    # ===== O'G'IL ISMLARI =====
    "abdulloh": "Allohning quli, Allohga bo'ysunuvchi",
    "abdurahmon": "Mehribon Allohning quli",
    "abdulaziz": "Ulug' Allohning quli",
    "abdullatif": "Latif Allohning quli",
    "abduqodir": "Qodir Allohning quli",
    "abdullo": "Allohning quli",
    "abdusalom": "Salom beruvchining quli",
    "abror": "Yaxshiliklar, ezgu ishlar",
    "abdulhamid": "Maqtovga loyiq Allohning quli",
    "abduljabbor": "Qahhor Allohning quli",
    "abdulkarim": "Karim Allohning quli",
    "abdulmalik": "Malik Allohning quli",
    "abdurashid": "Rashid Allohning quli",
    "abdulqahhor": "Qahhor Allohning quli",
    "abdulbasit": "Bosit Allohning quli",
    "abdulmo'min": "Mo'minlarning quli",
    "abulqosim": "Qosimning otasi",
    "adham": "Qora, ko'k",
    "adil": "Adolatli, haqqoniy",
    "adilbek": "Adolatli + bek",
    "adiljon": "Adolatli + jon",
    "ahmad": "Maqtovga sazovor",
    "ahmadjon": "Maqtovli + jon",
    "ahror": "Hur, erkin insonlar",
    "akbar": "Eng buyuk, ulkan",
    "akbarali": "Eng buyuk + Ali",
    "akbarbek": "Eng buyuk + bek",
    "akbarjon": "Eng buyuk + jon",
    "akmal": "Mukammal, to'liq",
    "alim": "Ilmli, bilimli",
    "alimbek": "Ilmli + bek",
    "alimjon": "Ilmli + jon",
    "ali": "Oliy, yuksak, yuqori martabali",
    "alibek": "Yuksak + bek",
    "alijon": "Yuksak + jon",
    "olim": "Bilimdon, olim inson",
    "olimjon": "Bilimdon + jon",
    "amir": "Podsho, buyruqchi, boshliq",
    "amirbek": "Boshliq + bek",
    "amirjon": "Podsho + jon",
    "amirali": "Podsho + Ali",
    "amin": "Ishonchli, ishonch bilan",
    "aminbek": "Ishonchli + bek",
    "aminjon": "Ishonchli + jon",
    "anas": "Do'st, sirdosh, inson",
    "anvar": "Yorqin, porloq, nurlanuvchi",
    "anvarbek": "Yorqin + bek",
    "anvarjon": "Yorqin + jon",
    "arbob": "So'z ustasi, ma'rifatli",
    "aslan": "Sher, jasur, baquvvat",
    "asomiddin": "Dinning himoyachisi",
    "ayub": "Sabrli, qaytgan",
    "azamat": "Ulug'vorlik, qadr-qimmat",
    "aziz": "Aziz, qadrli, hurmatli",
    "azizbek": "Aziz + bek",
    "azizjon": "Aziz + jon",
    "azim": "Ulug', buyuk, a'zam",
    "azimbek": "Buyuk + bek",
    "azimjon": "Ulug' + jon",
    "badriddin": "Dinning to'lin oyi",
    "bahodir": "Qahramon, jasur, botir",
    "bahodirbek": "Botir + bek",
    "bahrom": "G'alabali, zafarli",
    "baxtiyor": "Baxtli, baxtga erishgan",
    "bek": "Hukmdor, rahbar, lord",
    "bekzod": "Bekning farzandi",
    "bilol": "Toza suv, bilol",
    "botir": "Jasur, qo'rqmas",
    "botirjon": "Jasur + jon",
    "daler": "Jasur, botir, qo'rqmas",
    "daniyor": "Donishmand, aqlli",
    "danil": "Alloh mening hakamim",
    "davriddin": "Dinning asri",
    "dilmurod": "Dil + murod, ko'ngildagi murod",
    "dilshod": "Ko'ngli xursand, shod",
    "dilshodbek": "Xursand + bek",
    "dilshodjon": "Xursand + jon",
    "doston": "Hikoya, doston",
    "dostonbek": "Doston + bek",
    "dostonjon": "Doston + jon",
    "eldor": "El + dor, elni sevuvchi",
    "elshod": "El + shod, elni xursand qiluvchi",
    "elbek": "El + bek, el boshchisi",
    "elyor": "El yori, do'sti",
    "elmir": "El amiri",
    "elyorjon": "El yori + jon",
    "erkin": "Hur, erkin, ozod",
    "erkinbek": "Erkin + bek",
    "erkinjon": "Erkin + jon",
    "ernazar": "Erkak + nazar",
    "farrux": "Baxtli, farovon, yuzi yorqin",
    "fayzulloh": "Allohning fayzi, in'omi",
    "fayziddin": "Dinning fayzi",
    "farhod": "Qahramon, sevgi ramzi",
    "faridun": "Uch podshoh, adolatli",
    "firdavs": "Jannat bog'i, yuksak jannat",
    "fotih": "G'olib, ochuvchi",
    "fotihbek": "G'olib + bek",
    "fotihjon": "G'olib + jon",
    "furqat": "Ajralish, ayriliq",
    "g'ani": "Boy, boylik sohibi",
    "g'ulom": "Yigit, xizmatkor",
    "hamid": "Maqtovga loyiq",
    "hamidjon": "Maqtovli + jon",
    "hamza": "Sherdek jasur",
    "hasan": "Yaxshi, go'zal, husnli",
    "hasanali": "Yaxshi + Ali",
    "hasanbek": "Yaxshi + bek",
    "hasanjon": "Yaxshi + jon",
    "hikmat": "Donolik, aql-idrok",
    "hikmatulloh": "Allohning hikmati",
    "hoshim": "Non ushatuvchi, saxiy",
    "hoshimbek": "Hoshim + bek",
    "hoshimjon": "Hoshim + jon",
    "hotam": "Saxiy, mehmondo'st",
    "husniddin": "Dinning husni, go'zalligi",
    "idris": "O'qituvchi, ma'rifat sohibi",
    "ilmiddin": "Ilmli, dinni biluvchi",
    "imron": "Obod qiluvchi, farovon",
    "islom": "Islom diniga mansub, tinchlik",
    "islombek": "Islom + bek",
    "islomjon": "Islom + jon",
    "is'hok": "Kulgu, quvonch",
    "isroil": "Allohning bandasi",
    "izzat": "Hurmat, sharaf, qadr-qimmat",
    "izzatulloh": "Allohning izzati",
    "izzatbek": "Hurmat + bek",
    "izzatjon": "Hurmat + jon",
    "jobir": "Tuzatuvchi, qayta tiklovchi",
    "jasur": "Botir, qo'rqmas, jasur",
    "jasurbek": "Jasur + bek",
    "jasurjon": "Jasur + jon",
    "javlon": "Shovqin, jasorat",
    "jafar": "Kichik daryo, ko'p oqadigan",
    "jamoliddin": "Dinning go'zalligi",
    "jamshid": "Podshoh, yorqin",
    "jangir": "Jangchi, jang qiluvchi",
    "javohir": "Javohirlar, qimmatbaho toshlar",
    "jayhun": "Daryo nomi, katta daryo",
    "jura": "Jur'atli, jasur",
    "kamol": "Kamolga yetgan, mukammal",
    "kamoliddin": "Dinning kamoli",
    "karim": "Saxiy, karamli, rahmli",
    "karimbek": "Karim + bek",
    "karimjon": "Karim + jon",
    "kavus": "Podshoh, hukmdor",
    "komil": "Mukammal, yetuk",
    "komilbek": "Mukammal + bek",
    "komiljon": "Mukammal + jon",
    "kudrat": "Quvvat, kuch, qudrat",
    "kudratulloh": "Allohning qudrati",
    "lutfulla": "Allohning lutfi, mehribonligi",
    "lutfiddin": "Dinning lutfi",
    "madiyor": "Madhiya aytuvchi, maqtovchi",
    "majid": "Ulug', buyuk, shonli",
    "mahmud": "Maqtalgan, hamd etilgan",
    "mahmudjon": "Maqtalgan + jon",
    "mansur": "G'olib, g'alaba qozonuvchi",
    "mansurbek": "G'olib + bek",
    "mansurjon": "G'olib + jon",
    "maruf": "Yaxshi, ma'lum, tanilgan",
    "marufjon": "Yaxshi + jon",
    "mehribon": "Mehribon, shafqatli",
    "mehribonjon": "Mehribon + jon",
    "mardon": "Erkak, jasur, mard",
    "mardonbek": "Mard + bek",
    "mardonjon": "Mard + jon",
    "matlub": "Istak, tilak, arzu",
    "mumin": "Mo'min, ishongan, imonli",
    "muminjon": "Mo'min + jon",
    "murod": "Istak, orzu, tilak",
    "murodbek": "Murod + bek",
    "murodjon": "Murod + jon",
    "muzaffar": "G'olib, zafar qozonuvchi",
    "muzaffarjon": "G'olib + jon",
    "muhammad": "Maqtalgan, ko'p maqtalgan",
    "muhammadali": "Muhammad + Ali",
    "muhammadjon": "Muhammad + jon",
    "muhammadsolih": "Muhammad + solih",
    "muhammadsharif": "Muhammad + sharif",
    "muhsin": "Yaxshilik qiluvchi, ehsonchi",
    "mukammil": "Mukammal, to'liq yetgan",
    "muqim": "Doimiy, barqaror",
    "mustafo": "Tanlangan, saylangan",
    "mustafojon": "Tanlangan + jon",
    "murodulloh": "Allohning istagi",
    "najmiddin": "Dinning yulduzi",
    "nasriddin": "Dinning yordamchisi, g'alabasi",
    "na'mat": "Nemat, in'om, sovg'a",
    "na'matulloh": "Allohning nemati",
    "na'matjon": "Nemat + jon",
    "niyoz": "Tilak, arzu, xizmat",
    "niyozjon": "Niyoz + jon",
    "norbek": "Nur + bek",
    "norjon": "Nur + jon",
    "nosir": "Yordamchi, ko'makchi",
    "nuriddin": "Dinning nuri, yorug'ligi",
    "nurmuhamed": "Nur + Muhammad",
    "nurjon": "Nur + jon",
    "nuroli": "Nur + Ali",
    "obid": "Ibodat qiluvchi",
    "obidjon": "Ibodat qiluvchi + jon",
    "odil": "Adolatli, haqqoniy",
    "odilbek": "Adolatli + bek",
    "odiljon": "Adolatli + jon",
    "osman": "Haqiqiy, mustahkam",
    "qahramon": "Qahramon, botir, jasur",
    "qahramonjon": "Qahramon + jon",
    "qobil": "Qobiliyatli, qabul qilingan",
    "qobiljon": "Qobiliyatli + jon",
    "qodir": "Quvvatli, qodir",
    "qodirjon": "Quvvatli + jon",
    "rahim": "Mehribon, rahmli",
    "rahimjon": "Mehribon + jon",
    "rahmon": "Mehribon, rahmli (Alloh sifati)",
    "rahmonjon": "Rahmon + jon",
    "rahmatulloh": "Allohning rahmati",
    "rahmatjon": "Rahmat + jon",
    "rashid": "To'g'ri yo'ldagi, hidoyatli",
    "rashidjon": "Rashid + jon",
    "ravshan": "Yorqin, ravshan, ochiq",
    "ravshanjon": "Ravshan + jon",
    "rustam": "Pahlavon, kuchli, afsonaviy qahramon",
    "rustamjon": "Rustam + jon",
    "sadriddin": "Dinning sardori",
    "salim": "Sog'lom, salomat",
    "salimjon": "Sog'lom + jon",
    "sardor": "Boshliq, sardor, rahbar",
    "sardorjon": "Boshliq + jon",
    "sarvar": "Boshliq, rahnamo",
    "sarvarjon": "Boshliq + jon",
    "said": "Baxtli, saodatli",
    "saidjon": "Baxtli + jon",
    "shahobiddin": "Dinning yulduzi",
    "shahzod": "Shohzoda, qirol o'g'li",
    "shahzodjon": "Shohzoda + jon",
    "sharif": "Sharif, ulug', qadrli",
    "sharifjon": "Sharif + jon",
    "shokir": "Shukr qiluvchi, minnatdor",
    "shokirjon": "Shukr qiluvchi + jon",
    "shuhrat": "Shuhrat, dong, mashhurlik",
    "shuhratjon": "Shuhrat + jon",
    "siddiq": "Haqqoniy, chinchi",
    "sobir": "Sabrli, chidamli",
    "sobirjon": "Sabrli + jon",
    "sulaymon": "Tinchlik, salomatlik",
    "sulaymonjon": "Sulaymon + jon",
    "sulton": "Hukmdor, podshoh",
    "sultonjon": "Hukmdor + jon",
    "tahir": "Pok, toza, sof",
    "tahirjon": "Pok + jon",
    "tohir": "Pok, toza, pokiza",
    "tohirjon": "Pok + jon",
    "tojiddin": "Dinning toji",
    "to'lqin": "To'lqin, dengiz to'lqini",
    "tursun": "Tursin, yashasin (omad tilagi)",
    "tursunjon": "Tursin + jon",
    "umar": "Hayot, umr, uzoq yashovchi",
    "umarjon": "Umar + jon",
    "umid": "Umid, istak, orzu",
    "umidjon": "Umid + jon",
    "urfat": "Ulfat, do'stlik, yaqinlik",
    "urfatjon": "Do'stlik + jon",
    "usmon": "Mustahkam, osmon",
    "usmonjon": "Usmon + jon",
    "vali": "Do'st, avliyo, yaqin",
    "valijon": "Do'st + jon",
    "vohid": "Yagona, bir",
    "vohidjon": "Yagona + jon",
    "xayrulloh": "Allohning xayri",
    "xalil": "Do'st, yaqin, sirdosh",
    "xaliljon": "Do'st + jon",
    "xurshid": "Quyosh, porloq, yorqin",
    "xurshidjon": "Quyosh + jon",
    "xudoybergan": "Alloh bergan",
    "xurram": "Xursand, baxtli, quvonchli",
    "yahyo": "Hayot, tiriklik, yashash",
    "yahyojon": "Hayot + jon",
    "yasin": "Qur'on surasi nomi",
    "yoldosh": "Yo'ldosh, hamroh",
    "yoldoshjon": "Yo'ldosh + jon",
    "yulduz": "Yulduz, porloq",
    "yulduzjon": "Yulduz + jon",
    "yusuf": "Go'zal, chiroyli, Yusuf payg'ambar",
    "yusufjon": "Yusuf + jon",
    "zafar": "G'alaba, zafar, yengish",
    "zafarjon": "G'alaba + jon",
    "zakariyo": "Alloh eslab qo'ygan",
    "zamon": "Zamon, davr, vaqt",
    "zamonjon": "Zamon + jon",
    "zohid": "Zohid, dunyodan voz kechgan",
    "zohir": "Zohir, ravshan, ko'rinadigan",
    "zohirjon": "Zohir + jon",
    "zokir": "Zikr qiluvchi, eslab turuvchi",
    "zokirjon": "Zikr qiluvchi + jon",
    "zulfikar": "Ikki qirrali qilich, o'tkir",
    "ziyo": "Nur, yorug'lik, ziyo",
    "ziyojon": "Nur + jon",
    "ziyoviddin": "Dinning ziysi, nuri",
    "ziyodulla": "Allohning ziyosi, ortishi",

    # ===== QIZ ISMLARI =====
    "adiba": "Adibli, ma'rifatli, bilimdon",
    "afiza": "Pokiza, toza",
    "aisha": "Hayotli, tirik, yashovchi (payg'ambar xotini)",
    "ajarniso": "Mukofot + niso",
    "akbota": "Oq bo'ta, oq tuya bolasi",
    "albina": "Oq, oppoq, nurli",
    "alina": "Chiroyli, go'zal, yorqin",
    "almira": "Shohzoda, malika",
    "altinoy": "Oltin oy, oltindan qilingan oy",
    "amal": "Umid, orzu, istak",
    "aminah": "Ishonchli, ishonch bilan (payg'ambar onasi)",
    "amirabonu": "Amir + bonu, podshoh qizi",
    "anisa": "Do'st, sirdosh, yaqin",
    "anjelina": "Farishta, pok",
    "arzu": "Istak, tilak, orzu",
    "asalgul": "Asal + gul, shirin gul",
    "asaloy": "Asal + oy, shirin oy",
    "asima": "Himoyalangan, saqlangan",
    "asiya": "Ko'taruvchi, yuksak (Fir'avn xotini)",
    "asma": "Oliy, yuksak, baland",
    "atirgul": "Atir + gul, hidli gul",
    "aziza": "Qadrli, hurmatli, aziz",
    "bahora": "Bahor fasli, bahorgul",
    "baxora": "Xushbo'y hid, bahora gul",
    "baxtigul": "Baxt + gul",
    "barno": "Yosh, yigitlik",
    "begoyim": "Beka + oyim",
    "benafsha": "Binafsha guli",
    "bibi": "Xonim, ayol, ona",
    "dildora": "Dil sohibi, sevgan",
    "dilorom": "Dil + orom, ko'ngil tinchligi",
    "dilrabo": "Dil + rabo, dilni o'g'irlagan",
    "dilfuza": "Dil + fuza, ko'ngilni egallagan",
    "dilnoza": "Dil + noza, dilni bezagan",
    "dinora": "Oltin tanga, qiymatli",
    "durdona": "Durr + dona, marvarid",
    "edilar": "Sevgi, muhabbat",
    "farangiz": "Dunyoga mashhur",
    "farida": "Yagona, beqiyos, noyob",
    "fariha": "Xursand, quvnoq, xushhol",
    "fayruza": "Fayruza toshi",
    "fotima": "Sutdan ajratgan, pokiza (payg'ambar qizi)",
    "gul": "Gul, guldasta",
    "gulbahor": "Bahor guli",
    "gulchehra": "Gul + chehra, gul yuzli",
    "gulchin": "Gul + chin, guldasta",
    "guldasta": "Gul dastasi, guldasta",
    "gulnora": "Gul + nora, gul yorug'lik",
    "gulnoza": "Gul + noza, gul bezagi",
    "gulniso": "Gul + niso, gullar ayoli",
    "gulsum": "Qisqa sochli, go'zal",
    "gulzoda": "Gul + zoda, gul kabi qiz",
    "gulzora": "Gulzor, gul bog'i",
    "halima": "Sabrli, muloyim (payg'ambar onasi)",
    "hamida": "Maqtovga loyiq, maqtalgan",
    "hayot": "Hayot, tiriklik, yashash",
    "hijron": "Ayriliq, hijron",
    "hilola": "Yangi oy, hilol oy",
    "husniya": "Husnli, go'zal",
    "ibrat": "Sabab, ibrat, o'rnak",
    "ifor": "Xushbo'y hid, atir",
    "ilona": "Yorug'lik, nur",
    "inoyat": "Inoyat, lutf, mehribonlik",
    "irada": "Iroda, ixtiyor, xohish",
    "iroda": "Iroda, mustaqillik, kuchli xohish",
    "jannat": "Jannat, behisht, bog'",
    "jahon": "Dunyo, olam, jahon",
    "jahona": "Dunyo ayoli, jahon ayoli",
    "jamilya": "Go'zal, chiroyli, husnli",
    "jasmina": "Yasemin guli",
    "jasmin": "Yasemin, xushbo'y gul",
    "jumanazar": "Juma + nazar",
    "kamola": "Kamolga yetgan, mukammal ayol",
    "karima": "Saxiy, karamli, mehribon",
    "kimyo": "Kimyo, sirli narsa",
    "kumush": "Kumush, oq metall",
    "lola": "Lola guli, qizil gul",
    "laylo": "Tun, kecha (Layli va Majnun)",
    "lilya": "Lola gul, nilufar",
    "madina": "Madina shahri, pok shahar",
    "mahbuba": "Sevilgan, suyukli",
    "mahliqo": "Oy yuzli, go'zal",
    "malika": "Malika, shoh qizi",
    "mariya": "Maryam, pokiza",
    "mariyam": "Maryam, pokiza, toza",
    "marjona": "Marjon, qizil tosh",
    "marufabonu": "Marufa + bonu",
    "marufa": "Yaxshi, ma'lum, tanilgan",
    "marxabo": "Marhabo, salom",
    "mehrigul": "Mehribon + gul",
    "mehrinoz": "Mehribon + noz",
    "mehtargul": "Mehtar + gul",
    "minora": "Masjid minorasi",
    "mohtab": "Oy nuri, oy yorug'ligi",
    "munavvar": "Yorqin, nurli, porloq",
    "munisa": "Sirdosh, do'st, suhbatdosh",
    "munojot": "Duo, iltijo, yolvorish",
    "munira": "Yorqin, porloq, nurli",
    "murshida": "Yo'l ko'rsatuvchi, rahbar",
    "muslima": "Musulmon ayol, tinchlik sohibasi",
    "muqaddas": "Muqaddas, pok, muqaddas",
    "muyassar": "Oson, qulay, muyassar",
    "nargiza": "Nargiz guli",
    "narjis": "Nargiz guli, xushbo'y gul",
    "nasiba": "Nasibali, omadli",
    "nasima": "Nasim, shabada, yengil shamol",
    "nazakat": "Nazokat, noziklik, nafosat",
    "nazanin": "Nozik, nafis, go'zal",
    "nazira": "Andoza, namuna",
    "nazli": "Nozik, nazokatli",
    "nazgul": "Naza + gul",
    "nigora": "Rasm, surat, go'zal",
    "nilufar": "Nilufar guli, suv guli",
    "nodira": "Noyob, beqiyos, yagona",
    "nozanin": "Nozik, nafis, go'zal",
    "nozigul": "Nozik + gul",
    "nurbonu": "Nur + bonu",
    "nurgul": "Nur + gul",
    "nurxon": "Nur + xon",
    "nurniso": "Nur + nisa",
    "nuroy": "Nur + oy",
    "oybibi": "Oy + bibi",
    "oygul": "Oy + gul",
    "oydin": "Yorqin, ravshan",
    "oydina": "Yorqin ayol, nurli",
    "oyim": "Oyim, xonim, ona",
    "oyjan": "Oy + jan",
    "parizoda": "Parizoda, pari qizi",
    "parvin": "Yulduz, plevada",
    "pokiza": "Pok, toza, sof",
    "ra'no": "Nozik, go'zal, nafis",
    "rabiya": "Bahor, to'rtinchi (ayol valiy)",
    "rahima": "Mehribon, rahmli",
    "raziya": "Rozilik, qanoat, mamnun",
    "ruqiya": "Yuksalish, ko'tarilish",
    "rushana": "Yorqin, ravshan",
    "sabina": "Sabina, sabrli",
    "sabohat": "Go'zallik, husn, chiroy",
    "sabira": "Sabrli, chidamli",
    "sakina": "Tinchlik, osoyishtalik",
    "saida": "Baxtli, saodatli",
    "salmabonu": "Salma + bonu",
    "saltanat": "Saltanat, hukmronlik",
    "samara": "Meva, hosil, natija",
    "samira": "Do'st, suhbatdosh",
    "sanam": "Sanam, go'zal, but",
    "sara": "Sara, toza, pok",
    "sarvinaz": "Sarv + naz, sarv qaddi nozli",
    "sitora": "Yulduz, yulduzcha",
    "sofina": "Kema, safina",
    "sofia": "Donolik, hikmat",
    "sohiba": "Egasi, sohib, xo'jayin ayol",
    "soliha": "Yaxshi, solih, taqvodor",
    "sultana": "Sulton ayol",
    "sumayya": "Baland, yuksak (sahobiy ayol)",
    "surayyo": "Yulduzlar to'dasi, plevada",
    "tuhfa": "Sovg'a, hadya, in'om",
    "umida": "Umidli, orzuli",
    "xadija": "Vaqti oldin tug'ilgan (payg'ambar birinchi xotini)",
    "xayriniso": "Xayrli niso",
    "xayrunniso": "Xayrli ayol",
    "xolida": "Abadiy, doimiy",
    "xosiyat": "Foyda, foydali, sifat",
    "xurshida": "Quyosh, porloq (xurshid qiz varianti)",
    "yasmin": "Yasemin guli",
    "zahra": "Yorqin, porloq, gul (Fotima Zahra)",
    "zainab": "Otaning bezagi (payg'ambar qizi)",
    "zamira": "Yurak, qalb, vijdon",
}


# ═══════════════════════════════════════════════════════════
#  CHIROYLI GUI ILOVA
# ═══════════════════════════════════════════════════════════
class IsmManosiApp:
    def __init__(self, root):
        self.root = root
        self.root.title("✨ Ism Ma'nosi ✨")
        self.root.geometry("850x1080")
        self.root.resizable(False, False)
        self.root.configure(bg="#1a1a2e")

        # Ranglar
        self.COLOR_BG = "#1a1a2e"
        self.COLOR_FRAME = "#16213e"
        self.COLOR_INPUT_BG = "#0f3460"
        self.COLOR_TEXT = "#e6e6e6"
        self.COLOR_ACCENT = "#e94560"
        self.COLOR_GOLD = "#f0c040"
        self.COLOR_RESULT_BG = "#0a0a1a"

        self._build_ui()

    def _build_ui(self):
        # Sarlavha
        title_frame = tk.Frame(self.root, bg=self.COLOR_BG, pady=15)
        title_frame.pack(fill="x")

        tk.Label(
            title_frame,
            text="🌟 ISM MA'NOSI 🌟",
            font=("Segoe UI", 26, "bold"),
            bg=self.COLOR_BG,
            fg=self.COLOR_GOLD,
        ).pack()

        tk.Label(
            title_frame,
            text="Ismingizni kiriting va ma'nosini bilib oling!",
            font=("Segoe UI", 11),
            bg=self.COLOR_BG,
            fg="#8888aa",
        ).pack(pady=(2, 0))

        # Kiritish oynasi
        entry_frame = tk.Frame(self.root, bg=self.COLOR_FRAME, padx=30, pady=20)
        entry_frame.pack(fill="x", padx=20, pady=(10, 5))

        tk.Label(
            entry_frame,
            text="Ism kiriting:",
            font=("Segoe UI", 14, "bold"),
            bg=self.COLOR_FRAME,
            fg=self.COLOR_TEXT,
        ).pack(anchor="w")

        self.entry = tk.Entry(
            entry_frame,
            font=("Segoe UI", 16),
            bg=self.COLOR_INPUT_BG,
            fg="#ffffff",
            insertbackground="#ffffff",
            relief="flat",
            justify="center",
        )
        self.entry.pack(fill="x", pady=(8, 12), ipady=8)
        self.entry.bind("<Return>", lambda e: self.search())

        # Tugma
        btn = tk.Button(
            entry_frame,
            text="🔍 Ma'nosini topish",
            font=("Segoe UI", 13, "bold"),
            bg=self.COLOR_ACCENT,
            fg="#ffffff",
            activebackground="#c03040",
            activeforeground="#ffffff",
            relief="flat",
            cursor="hand2",
            command=self.search,
        )
        btn.pack(fill="x", ipady=8)

        # Natija oynasi
        result_frame = tk.Frame(self.root, bg=self.COLOR_FRAME, padx=25, pady=20)
        result_frame.pack(fill="both", expand=True, padx=20, pady=(5, 20))

        # Ism nomi
        self.lbl_name = tk.Label(
            result_frame,
            text="Ism: ____________",
            font=("Segoe UI", 20, "bold"),
            bg=self.COLOR_RESULT_BG,
            fg=self.COLOR_GOLD,
            anchor="w",
            relief="flat",
            padx=15,
            pady=12,
        )
        self.lbl_name.pack(fill="x", pady=(0, 10))

        # Ma'nosi
        self.lbl_meaning = tk.Label(
            result_frame,
            text="Ma'nosi: ____________",
            font=("Segoe UI", 14),
            bg=self.COLOR_RESULT_BG,
            fg=self.COLOR_TEXT,
            anchor="w",
            justify="left",
            wraplength=480,
            relief="flat",
            padx=15,
            pady=10,
        )
        self.lbl_meaning.pack(fill="both", expand=True)

        # Footer
        footer = tk.Label(
            self.root,
            text="📖 500+ ism mavjud  •  Barcha ismlar kiritilishi mumkin",
            font=("Segoe UI", 9),
            bg=self.COLOR_BG,
            fg="#555577",
        )
        footer.pack(side="bottom", pady=10)

        # Fokus
        self.entry.focus()

    def search(self):
        raw = self.entry.get().strip()
        if not raw:
            messagebox.showwarning("Ogohlantirish", "Iltimos, ism kiriting!")
            return

        key = raw.lower().strip()

        # 1) To'g'ridan-to'g'ri qidirish
        if key in ISMLAR:
            self._show(raw, ISMLAR[key])
            return

        # 2) Variantlar: "alibek" -> "ali" + "bek" bo'laklarga ajratish
        # Odatiy qo'shimchalar
        suffixes = ["bek", "jon", "ali", "boy", "xan", "hon", "oyim", "oy", "bibi", "bonu", "xon", "xonim", "zoda", "iddin", "ulloh", "ulla"]
        # Eng uzun suffixni topish
        found_suffix = None
        found_base = None
        for suf in sorted(suffixes, key=len, reverse=True):
            if key.endswith(suf):
                base = key[:len(key)-len(suf)]
                if base in ISMLAR:
                    found_suffix = suf
                    found_base = base
                    break

        if found_base:
            meaning = ISMLAR[found_base]
            full = f"{found_base.capitalize()} + {found_suffix.capitalize()}"
            # Agar qo'shimcha ham lug'atda bo'lsa, qo'shamiz
            if found_suffix in ISMLAR:
                meaning += f" | {found_suffix.capitalize()}: {ISMLAR[found_suffix]}"
            self._show(raw, f"{meaning}\n\n(Asosiy ism: {found_base.capitalize()}, qo'shimcha: {found_suffix.capitalize()})")
            return

        # 3) Murakkab ismlarni ikki qismga ajratish
        for i in range(3, len(key)-1):
            part1 = key[:i]
            part2 = key[i:]
            if part1 in ISMLAR and part2 in ISMLAR:
                m1 = ISMLAR[part1]
                m2 = ISMLAR[part2]
                self._show(raw, f"{part1.capitalize()}: {m1}\n{part2.capitalize()}: {m2}\n\n(Ism ikki qismdan tashkil topgan)")
                return

        # 4) Agar umuman topilmasa — umumiy javob
        self._show(raw, "Bu ism hozircha ma'lumotlar bazasida topilmadi.\n\n📌 Maslahat: Ilova 500+ ismni tanidi. Boshqa variantda yozib ko'ring yoki ismning to'liq shaklini kiriting.")

    def _show(self, name, meaning):
        self.lbl_name.config(text=f"Ism: {name}")
        self.lbl_meaning.config(text=f"Ma'nosi:\n{meaning}")
        self.lbl_meaning.update_idletasks()


if __name__ == "__main__":
    root = tk.Tk()
    app = IsmManosiApp(root)
    root.mainloop()